### ISSUE TITLE
indent the highlighting in the demo

### ISSUE THREAD

**Issue by benatkin** [NV/objectDiff.js#1]
Indenting the highlighting in the demo would make it easier to spot the level in the tree that the difference occurs at. For example, in the example the `a/b` (using [jsonpointer](https://github.com/janl/node-jsonpointer)) diff is one level deeper than the other diffs. Indenting the highlight block two and four characters could help show that.

**Comment by NV** [comment]
Fixed by d591a6c440bd3b40b5a61374465a3e489d3e2488
